#
# M A K E F I L E
# 

calibration:
	python camera-calibrate.py -i calibration-images -u calibration-images/calibration-01.jpg -c basler1920-computar5mm.p

clean:
	rm calibration-images/calibration-01_undistorted.jpg
	rm basler1920-computer5mm.p
