# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_image_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_image_set(object):
    def setupUi(self, select_image_set):
        select_image_set.setObjectName("select_image_set")
        select_image_set.resize(643, 460)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(select_image_set)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(select_image_set)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.image_sets = QtWidgets.QListWidget(select_image_set)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_sets.sizePolicy().hasHeightForWidth())
        self.image_sets.setSizePolicy(sizePolicy)
        self.image_sets.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.image_sets.setFont(font)
        self.image_sets.setObjectName("image_sets")
        self.verticalLayout.addWidget(self.image_sets)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageType = QtWidgets.QComboBox(select_image_set)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.imageType.setFont(font)
        self.imageType.setObjectName("imageType")
        self.horizontalLayout.addWidget(self.imageType)
        self.image_position = QtWidgets.QComboBox(select_image_set)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.image_position.setFont(font)
        self.image_position.setObjectName("image_position")
        self.horizontalLayout.addWidget(self.image_position)
        self.ok = QtWidgets.QPushButton(select_image_set)
        self.ok.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ok.setFont(font)
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(select_image_set)
        QtCore.QMetaObject.connectSlotsByName(select_image_set)

    def retranslateUi(self, select_image_set):
        _translate = QtCore.QCoreApplication.translate
        select_image_set.setWindowTitle(_translate("select_image_set", "Select Image Set"))
        self.label.setText(_translate("select_image_set", "Image Set"))
        self.ok.setText(_translate("select_image_set", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    select_image_set = QtWidgets.QDialog()
    ui = Ui_select_image_set()
    ui.setupUi(select_image_set)
    select_image_set.show()
    sys.exit(app.exec_())
