#!/bin/sh

WEEDSHOME=/home/weeds/jetson
cd $WEEDSHOME
export PYTHONPATH=/home/weeds/lib:/home/weeds/librealsense/build/wrappers/python
export OPENBLAS_CORETYPE=ARMv8
rm -rf /home/weeds/genicam_xml_cache
# THis is a complete hack to give the cameras time to come up
sleep 20
# This will only grab the images, no treatment
python3 $WEEDSHOME/weeds.py -o $WEEDSHOME/../output --logging logging-emitter.ini --grab --emitter

exit $?

