#!/bin/sh

WEEDSHOME=/home/weeds/jetson
export PYTHONPATH=/home/weeds/lib
export OPENBLAS_CORETYPE=ARMv8
# This will only grab the images, no treatment
python3 $WEEDSHOME/weeds.py -o $WEEDSHOME/../output --grab

exit $?

