# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog-init.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_initProgress(object):
    def setupUi(self, initProgress):
        initProgress.setObjectName("initProgress")
        initProgress.setWindowModality(QtCore.Qt.ApplicationModal)
        initProgress.resize(651, 221)
        self.verticalLayout = QtWidgets.QVBoxLayout(initProgress)
        self.verticalLayout.setObjectName("verticalLayout")
        self.initializationTask = QtWidgets.QLabel(initProgress)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.initializationTask.setFont(font)
        self.initializationTask.setObjectName("initializationTask")
        self.verticalLayout.addWidget(self.initializationTask)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.initiializationProgress = QtWidgets.QProgressBar(initProgress)
        self.initiializationProgress.setProperty("value", 0)
        self.initiializationProgress.setObjectName("initiializationProgress")
        self.verticalLayout.addWidget(self.initiializationProgress)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(initProgress)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(initProgress)
        self.buttonBox.accepted.connect(initProgress.accept) # type: ignore
        self.buttonBox.rejected.connect(initProgress.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(initProgress)

    def retranslateUi(self, initProgress):
        _translate = QtCore.QCoreApplication.translate
        initProgress.setWindowTitle(_translate("initProgress", "Initialization"))
        self.initializationTask.setText(_translate("initProgress", "Initializing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    initProgress = QtWidgets.QDialog()
    ui = Ui_initProgress()
    ui.setupUi(initProgress)
    initProgress.show()
    sys.exit(app.exec_())
